blank_issues_enabled: false
contact_links:
  - name: Contact form
    url: https://docs.google.com/forms/d/e/1FAIpQLSdsDaXjtcHDtqMgxr-KVnLBfBrzOXLyMRGiF0qSoNTFAttZVA/viewform
    about: 該当するカテゴリがない場合は、お問い合わせフォームからご連絡ください。
